# Generated by Django 3.0.7 on 2020-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(related_name='property', to='shop.Property', verbose_name='свойство'),
        ),
    ]
