# Generated by Django 3.0.7 on 2020-07-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInstancePropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название основы')),
                ('alias', models.CharField(db_index=True, max_length=200, verbose_name='Алиас')),
                ('slug', models.SlugField(unique=True)),
                ('icon_field', models.ImageField(blank=True, null=True, upload_to='basis_icon/', verbose_name='Изображение')),
                ('subcategories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Основа',
                'verbose_name_plural': 'Основы',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Свойство')),
                ('alias', models.CharField(db_index=True, max_length=200, verbose_name='Алиас')),
                ('slug', models.SlugField(unique=True)),
                ('product_type', models.ManyToManyField(related_name='product_types', to='shop.ProductType', verbose_name='Основа')),
            ],
            options={
                'verbose_name': 'Свойства',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='basis',
        ),
        migrations.DeleteModel(
            name='Basis',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='productinstancepropertyvalue',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productinstancepropertyvalue',
            name='properties',
            field=models.ManyToManyField(related_name='property', to='shop.PropertyType', verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basises', to='shop.ProductType', verbose_name='Основа'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['id', 'slug'], name='shop_proper_id_681176_idx'),
        ),
    ]
