# Generated by Django 3.0.7 on 2020-07-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200721_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstancepropertyvalue',
            options={'verbose_name': 'Значение', 'verbose_name_plural': 'Значения'},
        ),
        migrations.RemoveField(
            model_name='productinstancepropertyvalue',
            name='properties',
        ),
        migrations.AddField(
            model_name='productinstancepropertyvalue',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='shop.PropertyType', verbose_name='Свойство'),
        ),
        migrations.AddIndex(
            model_name='productinstancepropertyvalue',
            index=models.Index(fields=['id', 'value'], name='shop_produc_id_d56d00_idx'),
        ),
    ]
