# Generated by Django 3.0.7 on 2020-06-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200626_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='subcategories',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='categories',
        ),
    ]
