# Generated by Django 3.0.7 on 2020-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200722_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyType',
            new_name='Property',
        ),
        migrations.RenameModel(
            old_name='ProductInstancePropertyValue',
            new_name='Value',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='shop_proper_id_681176_idx',
        ),
        migrations.RemoveIndex(
            model_name='value',
            name='shop_produc_id_d56d00_idx',
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['id', 'slug'], name='shop_proper_id_0b90ab_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['id', 'value'], name='shop_value_id_975930_idx'),
        ),
    ]
