# Generated by Django 3.0.7 on 2020-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200630_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='data',
            field=models.CharField(max_length=200, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Свойство'),
        ),
    ]
