# Generated by Django 3.0.7 on 2020-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200722_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='product',
        ),
        migrations.AddField(
            model_name='value',
            name='product',
            field=models.ManyToManyField(related_name='products', to='shop.Product', verbose_name='Продукт'),
        ),
        migrations.RemoveField(
            model_name='value',
            name='properties',
        ),
        migrations.AddField(
            model_name='value',
            name='properties',
            field=models.ManyToManyField(related_name='property', to='shop.Property', verbose_name='Свойство'),
        ),
    ]
