# Generated by Django 3.0.7 on 2020-07-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200722_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='product',
        ),
        migrations.AddField(
            model_name='value',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product', verbose_name='Продукт'),
        ),
    ]
