# Generated by Django 3.0.7 on 2020-07-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200722_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='properties',
        ),
        migrations.AddField(
            model_name='value',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='shop.Property', verbose_name='Свойство'),
        ),
    ]
