# Generated by Django 3.0.7 on 2020-08-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200722_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='category',
            name='alias_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='alias_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='alias_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название основы'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название основы'),
        ),
        migrations.AddField(
            model_name='property',
            name='alias_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='property',
            name='alias_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='alias_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='alias_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название подкатегории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название подкатегории'),
        ),
        migrations.AddField(
            model_name='value',
            name='value_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='value',
            name='value_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='icon_field',
            field=models.ImageField(blank=True, null=True, upload_to='product_type_icon/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Значение'),
        ),
    ]
